# MHW03 Task 4 - SVD
Реализовать	на	Python SVD-разложение, как же без numpy :\

In [1]:
import numpy as np
import sympy as sp

In [2]:
# input Matrix A 
a_matrix = np.array([[3, 1, 1], [-1, 3, 1]], dtype=float)
print('\n input matrix: \n', a_matrix)

# Eigenvalue as a symbol
lamda = sp.symbols('lamda')

#Transponsing
a_transponse = a_matrix.transpose()
print('\n trasponse matrix: \n', a_transponse)


 input matrix: 
 [[ 3.  1.  1.]
 [-1.  3.  1.]]

 trasponse matrix: 
 [[ 3. -1.]
 [ 1.  3.]
 [ 1.  1.]]


# Algorytm SVD by functions

In [3]:
# Matrix dot
def matrix_dot(matrix1, matrix2):  
    return np.dot(matrix1, matrix2)

In [4]:
# Variables transorm into Symbols
def symbol_data(matrix_length):
    indexes = []
    for columns in np.arange(matrix_length):
        indexes.append(sp.symbols('x'+str(columns+1)))
    return indexes

In [5]:
# Main matrix equations
def matrix_equations(matrix, matrix_length, lammda, indexes):
    # Matrix equations
    main_equations = (np.dot(matrix,indexes) - np.dot(lamda,indexes))
    print("\n main equations:  \n", main_equations)

    # collect by symbols
    colected_exp = []
    for columns in np.arange(matrix_length):
        colected_exp.append(sp.collect(main_equations[columns], indexes))
    print("\n collect equations:  \n", colected_exp)

    # Eigenvalue zero matrix
    lamda_matrix = np.empty((matrix_length, matrix_length), dtype = object)

    # Input to matrix and collect by symbols
    for column in np.arange(matrix_length):
        for index in np.arange(matrix_length):
            lamda_matrix[column,index] = sp.N(colected_exp[column].coeff(indexes[index]),1)
    print("\n lamda matrix:  \n", lamda_matrix)

    # Determinant by symbols
    lamda_matrix_symbols = sp.Matrix(lamda_matrix)
    det_lambda = lamda_matrix_symbols.det()

    # Solving equation for Eigenvalue
    lamda_num = sp.solve(det_lambda, lamda)
    lamda_num = sorted(lamda_num, reverse=True)
    print("\n Eigenvalue value:  \n", lamda_num)
    
    return (lamda_num, colected_exp)

In [6]:
# Solving equations system for a eigen matrix
def solving_system(colected_expresion, matrix_length, lamda_numerical, lamda_symbol, indexes):
    
    # Substitution eigenvalue in equation system
    x_answers = np.empty((matrix_length, matrix_length), dtype = object)
    for lmda in np.arange(matrix_length):
        for column in np.arange(matrix_length):
            x_answers[lmda, column] = colected_expresion[column].subs(lamda_symbol, lamda_numerical[lmda])   
    print("\n Substitution Lambda value:  \n", x_answers)
    
    # Modify equation system, Defining in first equation x1 = 1
    value = 1
    for column in np.arange(matrix_length):
        for index in np.arange(matrix_length):
            x_answers[column, index] = x_answers[column, index].subs(indexes[0], (value)**column)
    print("\n Modify equation system for solving: x1 = {}".format(value),"\n", x_answers)    
    
    # Solving equation system for eigen matrix
    Nu_matrix = np.empty((matrix_length, matrix_length), dtype = float)

    for column in np.arange(matrix_length):
        for index in np.arange(matrix_length):
            Nu_matrix[column, index] = (sp.solve(x_answers[column],indexes)).get(indexes[index])
    Nu_matrix[:,0] = value
    print("\n Eigen matrix:  \n", Nu_matrix)
    
    return Nu_matrix

In [7]:
#Gram-Schmidt orthonormalization process:
def ortho_normalization(Nu_matrix, matrix_length):
    if matrix_length == 2:
        
        # Normalization of U matrix
        U_first_column = Nu_matrix[:,0] / np.linalg.norm(Nu_matrix[:,0])
        Wu = Nu_matrix[:,1] - np.dot(U_first_column,Nu_matrix[:,1]) * U_first_column
        U_second_column = Wu / np.linalg.norm(Wu)
        #print('\n First column:  ', U_first_column)
        #print(' Second column:  ', U_second_column)
     
        U_matrix = np.zeros((matrix_length, matrix_length), dtype = float)
        U_matrix[:,0] = U_first_column
        U_matrix[:,1] = U_second_column

        print('\n U matrix:  \n',U_matrix)
        return U_matrix
    
    elif matrix_length == 3:
        
        # Normalization of U matrix
        V_first_column = Nu_matrix[:,0] / np.linalg.norm(Nu_matrix[:,0])
        
        Wu = Nu_matrix[:,1] - np.dot(V_first_column,Nu_matrix[:,1]) * V_first_column
        V_second_column = Wu / np.linalg.norm(Wu)

        Wu1 = Nu_matrix[:,2] - np.dot(V_first_column,Nu_matrix[:,2]) * V_first_column - np.dot(V_second_column,Nu_matrix[:,2]) * V_second_column
        V_third_column = Wu1 / np.linalg.norm(Wu1)
        
        #print('\n First column:  ', V_first_column)
        #print(' Second column: ', V_second_column)
        #print(' Third column: ', V_third_column)

        V_matrix = np.zeros((matrix_length, matrix_length), dtype = float)
        V_matrix[:,0] = V_first_column
        V_matrix[:,1] = V_second_column
        V_matrix[:,2] = V_second_column
        
        print('\n V matrix:  \n',V_matrix)
        return V_matrix
        
    else: print('\n Sorry, but not this time :) \n') 

# Matrix U

In [8]:
print("\n U matrix \n ")

# Input matrix
matrix = matrix_dot(a_matrix,a_transponse)
# Column lenth
matrix_len = matrix.shape[0]
# Symbols variables
indexes = symbol_data(matrix_len)

# Matrix operations for Eigenvalue values
matrix_eq = matrix_equations(matrix, matrix_len, lamda, indexes)

# Solving equation system for a Eigen Matrix:
matrix_eigen = solving_system(matrix_eq[1], matrix_len, matrix_eq[0], lamda, indexes)

# U matrix:
U_matrix = ortho_normalization(matrix_eigen, matrix_len)


 U matrix 
 

 main equations:  
 [-lamda*x1 + 11.0*x1 + 1.0*x2 -lamda*x2 + 1.0*x1 + 11.0*x2]

 collect equations:  
 [x1*(-lamda + 11.0) + 1.0*x2, 1.0*x1 + x2*(-lamda + 11.0)]

 lamda matrix:  
 [[-lamda + 1.0e+1 1.]
 [1. -lamda + 1.0e+1]]

 Eigenvalue value:  
 [12.0000000000000, 10.0000000000000]

 Substitution Lambda value:  
 [[-1.0*x1 + 1.0*x2 1.0*x1 - 1.0*x2]
 [1.0*x1 + 1.0*x2 1.0*x1 + 1.0*x2]]

 Modify equation system for solving: x1 = 1 
 [[1.0*x2 - 1.0 -1.0*x2 + 1.0]
 [1.0*x2 + 1.0 1.0*x2 + 1.0]]

 Eigen matrix:  
 [[ 1.  1.]
 [ 1. -1.]]

 U matrix:  
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


# Matrix V

In [9]:
print("\n V matrix \n ")

# Input matrix
v_matrix = matrix_dot(a_transponse,a_matrix)
# Column lenth
v_matrix_len = v_matrix.shape[0]
# Symbols variables
v_indexes = symbol_data(v_matrix_len)

# Matrix operations for Eigenvalue values
v_matrix_eq = matrix_equations(v_matrix, v_matrix_len, lamda, v_indexes)

# Solving equation system for a Eigen Matrix:
v_matrix_eigen = solving_system(v_matrix_eq[1], v_matrix_len, v_matrix_eq[0], lamda, v_indexes)

# U matrix:
V_matrix = ortho_normalization(v_matrix_eigen, v_matrix_len)


 V matrix 
 

 main equations:  
 [-lamda*x1 + 10.0*x1 + 2.0*x3 -lamda*x2 + 10.0*x2 + 4.0*x3
 -lamda*x3 + 2.0*x1 + 4.0*x2 + 2.0*x3]

 collect equations:  
 [x1*(-lamda + 10.0) + 2.0*x3, x2*(-lamda + 10.0) + 4.0*x3, 2.0*x1 + 4.0*x2 + x3*(-lamda + 2.0)]

 lamda matrix:  
 [[-lamda + 1.0e+1 0 2.]
 [0 -lamda + 1.0e+1 4.]
 [2. 4. -lamda + 2.0]]

 Eigenvalue value:  
 [12.0000000000000, 10.0000000000000, 0.0]

 Substitution Lambda value:  
 [[-2.0*x1 + 2.0*x3 -2.0*x2 + 4.0*x3 2.0*x1 + 4.0*x2 - 10.0*x3]
 [2.0*x3 4.0*x3 2.0*x1 + 4.0*x2 - 8.0*x3]
 [10.0*x1 + 2.0*x3 10.0*x2 + 4.0*x3 2.0*x1 + 4.0*x2 + 2.0*x3]]

 Modify equation system for solving: x1 = 1 
 [[2.0*x3 - 2.0 -2.0*x2 + 4.0*x3 4.0*x2 - 10.0*x3 + 2.0]
 [2.0*x3 4.0*x3 4.0*x2 - 8.0*x3 + 2.0]
 [2.0*x3 + 10.0 10.0*x2 + 4.0*x3 4.0*x2 + 2.0*x3 + 2.0]]

 Eigen matrix:  
 [[ 1.   2.   1. ]
 [ 1.  -0.5  0. ]
 [ 1.   2.  -5. ]]

 V matrix:  
 [[ 0.57735027  0.40824829  0.40824829]
 [ 0.57735027 -0.81649658 -0.81649658]
 [ 0.57735027  0.40824829 

# Matrix S

In [10]:
# Eigenvalue values
eigen_unique_values = sorted(np.unique(matrix_eq[0] + v_matrix_eq[0]), reverse=True)

In [11]:
# Function for matrix (sqrt)
from math import sqrt 
def sqrt_round(element):
    return round(sqrt(element),1)    
vector_sqrt_round = np.vectorize(sqrt_round)

In [12]:
# Singular matrix
S_matrix = np.diag(vector_sqrt_round(eigen_unique_values))
print('\n S matrix:  \n',S_matrix)


 S matrix:  
 [[3.5 0.  0. ]
 [0.  3.2 0. ]
 [0.  0.  0. ]]
