# MHW03 Task 3 - LUP
Реализовать	на	Python LUP-разложение, Sorry не удержался сделал с numpy :\

In [1]:
import numpy as np
#from numpy import *

In [2]:
# input Matrix A, b in Ax = b 
a_matrix = np.array([[1, 2, 0],[3, 4, 4],[5, 6, 3]], dtype=float)
b_matrix = np.array([[3], [7], [8]], dtype=float)

In [3]:
# Functions

In [4]:
# # Sorting rows elements by column index 
# def sort_array(input_array, column):
#     new_array = np.copy(input_array)
#     return new_array[new_array[:,column].argsort()][::-1] # reversed - decreasing

In [5]:
# Sorting rows elements by column index and slicing
def sort_array(input_array, column):
    if column == 0:
        new_array = np.copy(input_array)
        return new_array[new_array[:,column].argsort()][::-1] # reversed - decreasing   
    else:
        low = input_array[column:,::].copy() # slice doesnt work with 0 args
        up = input_array[:column,::].copy()
        low_sorted = low[low[:,column].argsort()][::-1]
        return np.concatenate((up, low_sorted), axis=0) 

In [6]:
# Dividing row elements of array by column index
def divide_in_column(input_array, column, length_array):
    new_array = np.copy(input_array)
    #length_array = new_array.shape[0]
    for i in np.arange(column+1, length_array):
        new_array[i, column] = new_array[:,column][i] / new_array[:,column][column]
    return new_array

In [7]:
# Transforming by Shura addition
def tf_elements(input_array, column, length_array, depth_array):
    new_array = np.copy(input_array)
    #length_array = new_array.shape[0]
    #depth_array = new_array.shape[1]-1  # -1 need to save b Matrix
    depth_array = depth_array - 1 # -1 need to save b Matrix
    
    for col in range(column+1, depth_array):
        for row in range(column+1, length_array):
            new_array[:,col][row] = input_array[:,col][row] - (input_array[:,column][row] * input_array[column,:][col])
    
    return new_array

In [8]:
# Main algorythm

# Matrix equation Ax = b
all_matrix = np.append(a_matrix, b_matrix, axis=1)
print(' input matrix:\n', all_matrix)

# Matrix columns and diagonals for Shura addition
column_length = all_matrix.shape[0]
row_length = all_matrix.shape[1]
diagonal_elements = column_length - 1

# Diagonal matrix and Ax = b matrix join
matrix_diagonal = np.eye(column_length)
all_matrix_diagonal = np.concatenate((all_matrix, matrix_diagonal), axis=1)
print('\n input matrix and position matrix:\n', all_matrix_diagonal)

matrix = np.copy(all_matrix_diagonal)
for i in range(diagonal_elements):
    #Sorting
    matrix = sort_array(matrix, i)
    #Dividing
    column_array = divide_in_column(matrix, i, column_length)
    #Shura algorythm
    other_array = tf_elements(column_array, i, column_length, row_length)
    matrix = other_array  

print('\n after LUP algorytm:\n', matrix)

 input matrix:
 [[1. 2. 0. 3.]
 [3. 4. 4. 7.]
 [5. 6. 3. 8.]]

 input matrix and position matrix:
 [[1. 2. 0. 3. 1. 0. 0.]
 [3. 4. 4. 7. 0. 1. 0.]
 [5. 6. 3. 8. 0. 0. 1.]]

 after LUP algorytm:
 [[ 5.   6.   3.   8.   0.   0.   1. ]
 [ 0.2  0.8 -0.6  3.   1.   0.   0. ]
 [ 0.6  0.5  2.5  7.   0.   1.   0. ]]


In [9]:
# Matrix whithout b columb by slices

matrix_repositioning = matrix[::, row_length:].copy()
print(' matrix repositioning:\n', matrix_repositioning)

matrix = matrix[::, :row_length].copy()

matrix_out_b = matrix[::, :diagonal_elements+1].copy()
print('\n whithout b-matrix:\n', matrix_out_b)

matrix_only_b = matrix[::, diagonal_elements+1:].copy()
print('\n b-matrix:\n', matrix_only_b)

# Algorytm by iterations  = try not to use

# tmp_array = []
# for i, _ in enumerate(matrix):
#     tmp_array.append(matrix[i][:len(matrix)])
# matrix_out_b = np.array(tmp_array)
# print(matrix_out_b)

 matrix repositioning:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

 whithout b-matrix:
 [[ 5.   6.   3. ]
 [ 0.2  0.8 -0.6]
 [ 0.6  0.5  2.5]]

 b-matrix:
 [[8.]
 [3.]
 [7.]]


In [10]:
# Result Matrix decomposition

# Lower L matrix
L_no_diagonal = np.tril(matrix_out_b, k=-1) 
# Filling main diagonal by 1
np.fill_diagonal(L_no_diagonal, 1)
print('\n L-matrix:\n', L_no_diagonal)

# Upper U matrix
U_diagonal = np.triu(matrix_out_b, k=0) 
print('\n U-matrix:\n', U_diagonal)

# Repositions matrix
P_matrix = matrix_repositioning 
print('\n P-matrix:\n', matrix_repositioning)


 L-matrix:
 [[1.  0.  0. ]
 [0.2 1.  0. ]
 [0.6 0.5 1. ]]

 U-matrix:
 [[ 5.   6.   3. ]
 [ 0.   0.8 -0.6]
 [ 0.   0.   2.5]]

 P-matrix:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
